export const fi = 
{
  "abortti": 2,
  "anaali-": 2,
  "peräaukko": 1,
  "perse": 1,
  "ass-kusipää": 2,
  "kusipää": 1,
  "paskiaiset": 2,
  "pallokassi": 3,
  "narttu": 3,
  "nartut": 3,
  "tissit": 1,
  "rinnat": 1,
  "klitoris": 3,
  "n3keri": 5,
  "neger": 5,
  "nigr": 5,
  "paska": 3,
  "cum": 3,
  "cumshot": 4,
  "cunillingus": 3,
  "pahuksen": 1,
  "kalu": 2,
  "dildo": 3,
  "dildot": 3,
  "koira-kusipää": 2,
  "ejaculated": 3,
  "siemensyöksyn": 1,
  "siemensyöksy": 1,
  "väsyttää": 2,
  "fagging": 3,
  "risukimppuina": 3,
  "häpy": 2,
  "felching": 2,
  "fellatio": 4,
  "naida": 4,
  "fucked": 4,
  "fuckers": 4,
  "helvetin": 3,
  "fuckings": 3,
  "nussii": 2,
  "fudge-pakkaaja": 2,
  "helvetti": 3,
  "hore": 3,
  "kiimainen": 2,
  "jerk-off": 3,
  "kock": 2,
  "häpyhuulet": 3,
  "himo": 1,
  "masokisti": 2,
  "masturboida": 3,
  "äiti kusipää": 2,
  "natsi": 4,
  "nekru": 5,
  "neekerit": 5,
  "neekeri": 5,
  "n33keri": 5,
  "orgasim": 2,
  "orgasmi": 2,
  "orgasmeja": 2,
  "penis": 2,
  "kusta": 2,
  "kännissä": 1,
  "uloste":1,
  "porno": 2,
  "pornografia": 2,
  "pussies": 2,
  "pimppi": 3,
  "raiskata": 4,
  "raiskaaja": 4,
  "rimming": 2,
  "sadisti": 1,
  "ruuvaamalla": 1,
  "kivespussi": 2,
  "siemenneste": 3,
  "shag": 1,
  "shite": 1,
  "ripuli": 2,
  "shitted": 2,
  "skank": 2,
  "lutka": 2,
  "huoria": 3,
  "smegma": 3,
  "son-of-a-bitch": 3,
  "kives": 2,
  "tissi": 2,
  "titt": 2,
  "paskiainen": 3,
  "emätin": 2,
  "viagra": 1,
  "ulkosynnyttimet": 2,
  "wang": 1,
  "wank": 1,
  "huora": 2,
  "kehitysvammainen": 4,
  "kehari": 4,
}



export const fiGood = 
{
  "❤️": 4,
  ":peepoBlush": 2,
  "jeesus": 2,
  "rakastaa": 3,
  "rakastan teitä": 4,
  "minä rakastan": 3,
  "ei haukuta": 4,
  "ei kiusata": 4,
  "ei saa kiusata": 4,
  "😍": 2,
  "👍": 1,
  "hyvä pojat": 2,
  "hienosti tehty": 2,
  "Mikään ei ole mahdotonta": 3,
  "Jatka yrittämistä": 3,
  "less goo": 2,
  "lets go": 2,
}
